### ISSUE TITLE
Division doesn't result in a probability

### ISSUE THREAD

**Issue by joelsewhere** [learn-co-curriculum/dsc-mle#2]
Line 172 of the readme file shows a division that is meant to result in a probability. For this to result in a probability the denominator would need to be 100 not 10. 

**Current Code:**
```python
p_head = lst.count('Heads')/10
```

**Proposed Change:**
```python
p_head = lst.count('Heads')/100
```

**Comment by jessepisel** [comment]
Thanks for opening this issue @joelsewhere :wave:. I have implemented your proposed change with commit ffed22d29896e96b61e2e2bfd180b6f0d9eb77a6  so the division returns a probability between zero and one. I am closing this issue at this time.
